@echo off
echo Running E0-VERIFY...
poetry run python scripts/run_study.py E0-VERIFY --stage verify --wandb-mode disabled

echo Running tiny E1...
poetry run python scripts/run_study.py E1-IID-CS --stage smoke --wandb-mode disabled --seeds 42

echo Running tiny E2...
poetry run python scripts/run_study.py E2-IID-OSR --stage smoke --wandb-mode disabled --seeds 42

echo Running Legacy PR smoke...
poetry run python scripts/run.py +study=A4-PR method=fedtros_pr_legacy stage=smoke tracking.backend=local dataset.preprocessing.num_clients=2 federated.server.num_rounds=1
