name: cpu
device_prefer: cpu
allow_cpu_fallback: true
move_data_to_device: false
deterministic: true
benchmark: false
use_deterministic_algorithms: false
client_num_cpus: 1
client_num_gpus: 0.0
simulation_gpu_batches:
  enabled: false
  batch_size: 1
