name: full
device_prefer: gpu
allow_cpu_fallback: false
move_data_to_device: true
deterministic: true
benchmark: false
use_deterministic_algorithms: false
client_num_cpus: 4
client_num_gpus: 1.0
simulation_gpu_batches:
  enabled: true
  batch_size: 1

