name: gpu
device_prefer: gpu
allow_cpu_fallback: false
move_data_to_device: false
deterministic: true
benchmark: true
use_deterministic_algorithms: false
client_num_cpus: 1
client_num_gpus: 1.0
simulation_gpu_batches:
  enabled: false
  batch_size: 50
